---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by baggiowang.
--- DateTime: 2020/6/30 6:48 下午i
---

local BuildNest = import("UI/MainCity/BuildRelated/BuildAnim/BuildNest")

local BuildBeastBase = fgui.extension_class(GButton)
fgui.register_extension("ui://Build/Building440000", BuildBeastBase)

function BuildBeastBase:ctor()
end

function BuildBeastBase:ChangeLockStatus()
    if Model.Player.Level >= 8 or Model.Player.isUnlockKingkong then
        if self.parent._itemLock then 
            self.parent._itemLock:SetStateUnlock()
            self.parent._itemLock._anim:Play()
        end
    end
end

function BuildBeastBase:BuildUnLock()
    if Model.Player.Level >= 8 or Model.Player.isUnlockKingkong then
        --巢穴解锁
        local upgrade_func = function(rsp)
            if self.parent._itemLock then
                self.parent._itemLock:RemoveFromParent()
                self.parent._itemLock = nil
            end
            self.parent:UpgradeEnd(rsp.Building.Level)
            BuildNest.CheckNestUnlock(Global.BuildingGodzilla)
        end
        Net.Buildings.Upgrade(self.parent.building.Id, true, upgrade_func)
    else
        local conf = ConfigMgr.GetItem("configBuildings", self.parent.building.ConfId)
        local data = {
            base_name = BuildModel.GetName(Global.BuildingCenter),
            base_level = 8
        }
        TipUtil.TipById(30602, data)
    end
end

return BuildBeastBase